export const LOAD_STATE = 'GAMEBOARD/LOAD_STATE';
export const MOVE = 'GAMEBOARD/MOVE';
export const NO_MORE_MOVES = 'GAMEBOARD/NO_MORE_MOVES';
export const ROTATE_PLAYER = 'GAMEBOARD/ROTATE_PLAYER';
export const SKIP_MOVE = 'GAMEBOARD/SKIP_MOVE';
export const START_NEW_GAME = 'GAMEBOARD/START_NEW_GAME';
export const STOP_GAME = 'GAMEBOARD/STOP_GAME';
export const UPDATE_AVAILABLE_MOVES = 'GAMEBOARD/UPDATE_AVAILABLE_MOVES';
